name: nm_gql_go_link
description: A new flutter plugin project.
version: 0.0.1
homepage: https://github.com/google/note-maps/blob/main/packages/nm_gql_go_link

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  gql_link: ^0.3.0
  gql_exec: 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        pluginClass: NmGqlGoLinkPlugin
        package: com.example.nm_gql_go_link
      ios:
        pluginClass: NmGqlGoLinkPlugin
      linux:
        pluginClass: NmGqlGoLinkPlugin
      macos:
        pluginClass: NmGqlGoLinkPlugin
