name: quilljs_webview
description: Provides a QuillJS editor wrapped in a WebView
version: 0.0.1
homepage: https://github.com/google/note-maps/tree/master/packages/quilljs_webview

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^0.3.22+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - third_party/quilljs/quill.bubble.css
    - third_party/quilljs/quill.core.css
    - third_party/quilljs/quill.min.js
    - third_party/quilljs/quill.snow.css
